AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tier-2: Intermediate Challenge - AWS ECS - ECR Stack

Resources:
  MyContainerRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: emercado-tier2-ecr-repository
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              Service: 
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
                - codedeploy.amazonaws.com
                - s3.amazonaws.com
                - cloudformation.amazonaws.com
                - ecs-tasks.amazonaws.com
                - ecs.amazonaws.com
            Action: '*'
              # - "ecr:GetDownloadUrlForLayer"
              # - "ecr:BatchGetImage"
              # - "ecr:BatchCheckLayerAvailability"
              # - "ecr:PutImage"
              # - "ecr:InitiateLayerUpload"
              # - "ecr:UploadLayerPart"
              # - "ecr:CompleteLayerUpload"