AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tier-2: Intermediate Challenge - AWS ECS - ECR Stack

Resources:
  MyContainerRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: emercado-tier2-ecr-repository
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: "*"
            Action: '*'
              # - "ecr:GetDownloadUrlForLayer"
              # - "ecr:BatchGetImage"
              # - "ecr:BatchCheckLayerAvailability"
              # - "ecr:PutImage"
              # - "ecr:InitiateLayerUpload"
              # - "ecr:UploadLayerPart"
              # - "ecr:CompleteLayerUpload"

Outputs:
  ECRRepo:
    Description: A reference to the ECR repository
    Value: !Ref MyContainerRepository
    Export:
      Name: ECRRepoName

  ECRTag:
    Description: A reference to the ECR repository tag
    Value: latest
    Export:
      Name: ECRTagName